<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import AppShell from '@/components/AppShell.vue'
import PageState from '@/components/PageState.vue'
import { getAdminSummary, type AdminSummary } from '@/api/admin'
const router=useRouter();const summary=ref<AdminSummary>();const loading=ref(false);const error=ref('')
async function load(){loading.value=true;error.value='';try{summary.value=(await getAdminSummary()).data}catch(e:any){error.value=e?.response?.data?.message||'看板加载失败'}finally{loading.value=false}}onMounted(load)
</script>
<template><AppShell title="管理看板"><PageState :loading="loading" :error="error" @retry="load"><div v-if="summary" class="stats"><article class="surface-card"><strong>{{summary.pending}}</strong><span>待审核活动</span><el-button text type="primary" @click="router.push('/admin/review')">前往审核</el-button></article><article class="surface-card"><strong>{{summary.published}}</strong><span>已发布活动</span><el-button text type="primary" @click="router.push('/admin/activities')">浏览活动</el-button></article><article class="surface-card"><strong>{{summary.sources}}</strong><span>数据源</span><el-button text type="primary" @click="router.push('/admin/data-sources')">管理数据源</el-button></article><article class="surface-card"><strong>{{summary.failed_tasks}}</strong><span>异常任务</span><el-button text type="primary" @click="router.push('/admin/audit-logs')">查看审计</el-button></article></div><section class="surface-card shortcuts"><h2>管理工具</h2><el-button @click="router.push('/admin/activities')">活动管理</el-button><el-button @click="router.push('/admin/review')">审核队列</el-button><el-button @click="router.push('/admin/publisher-applications')">发起人申请</el-button><el-button @click="router.push('/admin/data-sources')">数据源</el-button><el-button @click="router.push('/admin/knowledge')">词表与知识节点</el-button><el-button @click="router.push('/admin/audit-logs')">审计日志</el-button></section></PageState></AppShell></template>
<style scoped>.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.stats article{padding:22px;display:grid;gap:8px}.stats strong{color:var(--brand);font-size:32px}.stats span{color:var(--text-muted)}.shortcuts{padding:22px;margin-top:20px}.shortcuts h2{margin:0 0 14px;color:var(--brand-dark)}@media(max-width:800px){.stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:440px){.stats{grid-template-columns:1fr}}</style>
